### ISSUE TITLE
Syntax error when running setup.py to install deepinpy via pip

### ISSUE THREAD

**Issue by ibex-training** [utcsilab/deepinpy#18]
Trying to install via...
```
pip install git+https://github.com/utcsilab/deepinpy.git#egg=deepinpy
```
...yields an error due to missing comma.
```
Collecting deepinpy
  Cloning https://github.com/utcsilab/deepinpy.git to /tmp/pip-install-0j1rvto2/deepinpy

Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /home/ibex-training/conda-examples/deepinpy-example-project/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0j1rvto2/deepinpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0j1rvto2/deepinpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-scz3vtu0
         cwd: /tmp/pip-install-0j1rvto2/deepinpy/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0j1rvto2/deepinpy/setup.py", line 8
        version="0.0.1",
        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by jtamir** [comment]
Thanks. I can fix this but I believe you already have a fix? Would you prefer to submit a PR?
